stages: [test, build, deploy, notify]

test:
  stage: test
  image: ${runtime.base_image}
  script:
${ci.gitlab_ci.test_script}

build_image:
  stage: build
  image: docker:27
  services: [docker:27-dind]
  script:
${ci.gitlab_ci.build_script}

deploy:
  stage: deploy
# initree:if deploy.runtime_image
  image: ${deploy.runtime_image}
# initree:endif
  script:
${ci.gitlab_ci.deploy_script}

# initree:if notify.send_recipe
notify:
  stage: notify
  when: on_success
  script:
${ci.gitlab_ci.notify_script}
# initree:endif
