apiVersion: v1
kind: Service
metadata:
  name: ${container.image_name}
  namespace: ${deploy.k8s.namespace}
spec:
  selector:
    app: ${container.image_name}
  ports:
    - port: 80
      targetPort: ${container.exposed_port}
